In [23]:
## 306 project
#install.packages("dplyr")
library(dplyr)
#install.packages("ggplot2")
library(ggplot2)

Installing package into ‘/home/jupyter/R/x86_64-pc-linux-gnu-library/4.5’
(as ‘lib’ is unspecified)

In [28]:
yield_data = read.csv("cereal-crop-yield-vs-fertilizer-application.csv")
co_data = read.csv("co-emissions-per-capita.csv")
gdp_data = read.csv("gdp-per-capita-worldbank.csv")

In [39]:
filtered_yield <- filter(yield_data, Year > 2020)
avg_yield <- filtered_yield %>% group_by(Entity) %>% summarize(mean_yield = mean(Cereal.yield))
head(avg_yield)

  Entity         mean_yield
1 Afghanistan    2.238525
2 Africa         1.706862
3 Africa (FAO)   1.706875
4 Albania        5.167025
5 Algeria        1.456850
6 Americas (FAO) 5.929450

In [37]:
filtered_co <- filter(co_data, Year > 2020)
avg_co <- filtered_co %>% group_by(Entity) %>% summarize(mean_co = mean(CO..emissions.per.capita))
head(avg_co)

  Entity      mean_co
1 Afghanistan 0.2512173
2 Africa      1.0122457
3 Albania     1.6391484
4 Algeria     4.2334172
5 Andorra     5.2363044
6 Angola      0.5819078

In [40]:
filtered_gdp <- filter(gdp_data, Year > 2020)
avg_gdp <- filtered_gdp %>% group_by(Entity) %>% summarize(mean_gdp = mean(GDP.per.capita))
head(avg_gdp)

  Entity              mean_gdp
1 Afghanistan          2036.563
2 Albania             19930.963
3 Algeria             14985.077
4 Andorra             63451.297
5 Angola               8875.643
6 Antigua and Barbuda 27883.241